/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pt.ipleiria.estg.dei.es.minesfinder;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutput;
import java.io.ObjectOutputStream;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;

/**
 *
 * @author Rui
 */
public class MinesFinder extends javax.swing.JFrame{

    private TabelaRecordes recordesFacil;
    private TabelaRecordes recordesMedio;
    private TabelaRecordes recordesDificil;
    /**
     * Creates new form MinesFinder
     */
    public MinesFinder() {
        initComponents();
        this.recordesFacil = new TabelaRecordes();
        this.recordesMedio = new TabelaRecordes();
        this.recordesDificil = new TabelaRecordes();
        lerRecordesDisco();

        label_nomeFacil.setText(recordesFacil.getNome());
        label_pontFacil.setText(Long.toString(recordesFacil.getTempo()/1000));
        label_nomeMedio.setText(recordesMedio.getNome());
        label_pontMedio.setText(Long.toString(recordesMedio.getTempo()/1000));
        label_nomeDificil.setText(recordesDificil.getNome());
        label_pontDificil.setText(Long.toString(recordesDificil.getTempo()/1000));
        
        recordesFacil.addTabelaRecordesListener(new TabelaRecordesListener() {
            @Override
            public void recordesAtualizados(TabelaRecordes recordes){
                recordesFacilAtualizado(recordes);
            }
        });
        
        recordesMedio.addTabelaRecordesListener(new TabelaRecordesListener() {
            @Override
            public void recordesAtualizados(TabelaRecordes recordes) {
                recordesMedioAtualizado(recordes);
            }
        });
        
        recordesDificil.addTabelaRecordesListener(new TabelaRecordesListener() {
            @Override
            public void recordesAtualizados(TabelaRecordes recordes) {
                recordesDificilAtualizado(recordes);
            }
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        label_nomeFacil = new javax.swing.JLabel();
        label_pontFacil = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        label_nomeMedio = new javax.swing.JLabel();
        label_pontMedio = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        label_nomeDificil = new javax.swing.JLabel();
        label_pontDificil = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        button_facil = new javax.swing.JButton();
        button_medio = new javax.swing.JButton();
        button_dificil = new javax.swing.JButton();
        button_sair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setBackground(new java.awt.Color(102, 102, 255));
        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("MinesFinder v1.0");
        jLabel2.setToolTipText("");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("RECORDES");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Facil");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        label_nomeFacil.setText("Nome jogador");

        label_pontFacil.setText("9999");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Medio");

        label_nomeMedio.setText("Nome jogador");

        label_pontMedio.setText("9999");

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Dificil");

        label_nomeDificil.setText("Nome jogador");

        label_pontDificil.setText("9999");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(label_nomeDificil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label_pontDificil))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(label_nomeFacil)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(label_pontFacil))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(label_nomeMedio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label_pontMedio)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_nomeFacil)
                    .addComponent(label_pontFacil))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_nomeMedio)
                    .addComponent(label_pontMedio))
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_nomeDificil)
                    .addComponent(label_pontDificil))
                .addContainerGap(194, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_START);

        jPanel2.setBackground(new java.awt.Color(255, 255, 153));
        jPanel2.setLayout(new java.awt.GridLayout(2, 2, 1, 1));

        button_facil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pt/ipleiria/estg/dei/es/minesfinder/minas_facil.png"))); // NOI18N
        button_facil.setText("Facil");
        button_facil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_facilActionPerformed(evt);
            }
        });
        jPanel2.add(button_facil);

        button_medio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pt/ipleiria/estg/dei/es/minesfinder/minas_medio.png"))); // NOI18N
        button_medio.setText("Medio");
        button_medio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_medioActionPerformed(evt);
            }
        });
        jPanel2.add(button_medio);

        button_dificil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pt/ipleiria/estg/dei/es/minesfinder/minas_dificil.png"))); // NOI18N
        button_dificil.setText("Dificil");
        button_dificil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_dificilActionPerformed(evt);
            }
        });
        jPanel2.add(button_dificil);

        button_sair.setText("Sair");
        button_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_sairActionPerformed(evt);
            }
        });
        jPanel2.add(button_sair);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_facilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_facilActionPerformed
        JanelaDeJogo janela = new JanelaDeJogo(new CampoMinado(9,9,10), recordesFacil);
        janela.setVisible(true);
    }//GEN-LAST:event_button_facilActionPerformed

    private void button_medioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_medioActionPerformed
        JanelaDeJogo janela = new JanelaDeJogo(new CampoMinado(3,3,1), recordesMedio);
        janela.setVisible(true);
    }//GEN-LAST:event_button_medioActionPerformed

    private void button_dificilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_dificilActionPerformed
        JanelaDeJogo janela = new JanelaDeJogo(new CampoMinado(32,16,90), recordesDificil); 
        janela.setVisible(true);
    }//GEN-LAST:event_button_dificilActionPerformed

    private void button_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_sairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_button_sairActionPerformed

    private void recordesFacilAtualizado(TabelaRecordes recordes){
        label_nomeFacil.setText(recordes.getNome());
        label_pontFacil.setText(Long.toString(recordes.getTempo()/1000));
        guardarRecordesDisco();
    }
    private void recordesMedioAtualizado(TabelaRecordes recordes){
        label_nomeMedio.setText(recordes.getNome());
        label_pontMedio.setText(Long.toString(recordes.getTempo()/1000));
        guardarRecordesDisco();
    }
    private void recordesDificilAtualizado(TabelaRecordes recordes){
        label_nomeDificil.setText(recordes.getNome());
        label_pontDificil.setText(Long.toString(recordes.getTempo()/1000));
        guardarRecordesDisco();
    }
    
    private void guardarRecordesDisco(){
        ObjectOutputStream oos = null;
        try{
            File f=new File(System.getProperty("user.home") + File.separator + "minesfinder.recordes");
            oos = new ObjectOutputStream(new FileOutputStream(f));
            oos.writeObject(recordesFacil);
            oos.writeObject(recordesMedio);
            oos.writeObject(recordesDificil);
            oos.close();
        } catch (IOException ex){
            System.getLogger(MinesFinder.class.getName()).log(Level.WARNING, ex);
        }
    }
    
    private void lerRecordesDisco(){
        ObjectInputStream ois = null;
        File f = new File(System.getProperty("user.home") + File.separator + "minesfinder.recordes");
        if(f.canRead()){
            try{
                ois = new ObjectInputStream(new FileInputStream(f));
                recordesFacil = (TabelaRecordes) ois.readObject();
                recordesMedio = (TabelaRecordes)ois.readObject();
                recordesDificil = (TabelaRecordes)ois.readObject();
                ois.close();
            } catch(IOException ex){
                //Logger.getLogger(MinesFinder.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                java.util.logging.Logger.getLogger(MinesFinder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MinesFinder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MinesFinder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MinesFinder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MinesFinder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MinesFinder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_dificil;
    private javax.swing.JButton button_facil;
    private javax.swing.JButton button_medio;
    private javax.swing.JButton button_sair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel label_nomeDificil;
    private javax.swing.JLabel label_nomeFacil;
    private javax.swing.JLabel label_nomeMedio;
    private javax.swing.JLabel label_pontDificil;
    private javax.swing.JLabel label_pontFacil;
    private javax.swing.JLabel label_pontMedio;
    // End of variables declaration//GEN-END:variables
}
